using System.Collections.Generic;
using UnityEngine;

public class WorldGenMarching : MonoBehaviour
{
    public int WorldSizeInChunks = 10;
  

    Dictionary<Vector3Int, MarchingChunk> chunks = new Dictionary<Vector3Int, MarchingChunk>();
   
    void Start()
    {
        Generate();
    }

    void Generate()
    {
        for (int x = 0; x < WorldSizeInChunks; x++)
        {
            for (int z = 0; z < WorldSizeInChunks; z++)
            {
                Vector3Int chunkPos = new Vector3Int(x * GameData.ChunkWidth, 0, z * GameData.ChunkWidth);
                chunks.Add(chunkPos, new MarchingChunk(chunkPos));
                chunks[chunkPos].chunkObject.transform.SetParent(transform);
            }
        }

        Debug.Log(string.Format("{0} x {0} world generated", (WorldSizeInChunks * GameData.ChunkWidth))); // Just shows the world generated by meters


    }

    public MarchingChunk GetChunkFromV3 (Vector3 pos)
    {
        int x = (int)pos.x;
        int y = (int)pos.y;
        int z = (int)pos.z;

        return chunks[new Vector3Int(x, y, z)];

    }


}

  
