using System.Collections.Generic;
using Unity.Collections;
using Unity.Mathematics;
using UnityEngine;

public class WorldGenMarching : MonoBehaviour
{
    public int WorldSizeInChunks = 10;
    private HashSet<Vector3Int> chunksRebuiltinFrame = new HashSet<Vector3Int>();
    public int HeightInChunksWorld = 2;

    public static NativeArray<int3> cornerTableNative;
    public static NativeArray<int2> EdgeIndexesNative;
    public static NativeArray<int> TriangleTableFlatNative;

    private void Awake()
    {
        int[,] table2D = GameData.TriangleTable;
        int LengthInTotal = table2D.GetLength(0) * table2D.GetLength(1);
        int[] flatTable = new int[LengthInTotal];
        for (int i = 0; i < table2D.GetLength(0); i++)
            for (int j = 0; j < table2D.GetLength(1); j++)
                flatTable[i * table2D.GetLength(1) + j] = table2D[i, j];

        //Creating NativeArrays
        cornerTableNative = new NativeArray<int3>(GameData.CornerTable.Length, Allocator.Persistent);
        for (int i = 0; i < GameData.CornerTable.Length; i++)
            cornerTableNative[i] = new int3(
                GameData.CornerTable[i].x,
                GameData.CornerTable[i].y,
                GameData.CornerTable[i].z);

        EdgeIndexesNative = new NativeArray<int2>(GameData.EdgeIndexes.GetLength(0), Allocator.Persistent);
        for (int i = 0; i < GameData.EdgeIndexes.GetLength(0); i++)
            EdgeIndexesNative[i] = new int2(
                GameData.EdgeIndexes[i, 0],
                GameData.EdgeIndexes[i, 1]);
        TriangleTableFlatNative = new NativeArray<int>(flatTable, Allocator.Persistent);

        GameData.InitNativeArrayTables();
    }




    Dictionary<Vector3Int, MarchingChunk> chunks = new Dictionary<Vector3Int, MarchingChunk>();
   
    void Start()
    {
       
        int mapWidth = WorldSizeInChunks * GameData.ChunkWidth + 1;
        int mapHeight = HeightInChunksWorld * GameData.ChunkHeight + 1;
        int mapDepth = WorldSizeInChunks * GameData.ChunkWidth + 1;

        GameData.GlobalTerrainMap = new float[mapWidth, mapHeight, mapDepth];
        GameData.TerrainMapOffset = new Vector3Int(mapWidth / 2, 0, mapDepth / 2);

        

        Generate();
    }

    private void OnDestroy()
    {
        if (cornerTableNative.IsCreated) cornerTableNative.Dispose();
        if (EdgeIndexesNative.IsCreated) EdgeIndexesNative.Dispose();
        if (TriangleTableFlatNative.IsCreated) TriangleTableFlatNative.Dispose();

    }

    private void OnApplicationQuit()
    {
        GameData.DisposeTables();
    }

    void Generate()
    {
        int totalWorldHeight = HeightInChunksWorld * GameData.ChunkHeight;
        
        int centerworld = (WorldSizeInChunks * GameData.ChunkWidth) / 2;

        for (int x = 0; x < WorldSizeInChunks; x++)
        {
            for (int z = 0; z < WorldSizeInChunks; z++)

            {
                for (int y = 0; y < HeightInChunksWorld; y++)
                {
                    int worldX = x * GameData.ChunkWidth - centerworld;
                    int worldY = y * GameData.ChunkHeight - totalWorldHeight / 2;
                    int worldZ = z * GameData.ChunkWidth - centerworld;

                    Vector3Int chunkPos = new Vector3Int(worldX, worldY, worldZ);

                    MarchingChunk chunk = new MarchingChunk(chunkPos, GameData.GlobalTerrainMap, this);

                    chunk.world = this;

                    chunks.Add(chunkPos, chunk);
                    chunk.chunkObject.transform.SetParent(transform);
                }
            }
        }

        Debug.Log(string.Format("{0} x {0} world generated", (WorldSizeInChunks * GameData.ChunkWidth))); // Just shows the world generated by meters


    }

    private System.Collections.IEnumerator DelayRebuild(MarchingChunk chunk, float delay)
    {
        yield return new WaitForSeconds(delay);
        yield return chunk.RebuildMeshAsync();
    }

    

    public MarchingChunk GetChunkFromV3 (Vector3 pos)
    {
        Vector3Int key = new Vector3Int(
            Mathf.FloorToInt(pos.x / GameData.ChunkWidth) * GameData.ChunkWidth,
            0,
            Mathf.FloorToInt(pos.z / GameData.ChunkWidth) * GameData.ChunkWidth);

        return chunks.TryGetValue (key, out var chunk) ? chunk : null;

    }

    public void RebuildNeighbourChunks(Vector3Int chunkPos, bool includeSelf = false)
    {
        Vector3Int[] directions = new Vector3Int[]
        {
            new Vector3Int(GameData.ChunkWidth, 0, 0),
            new Vector3Int(-GameData.ChunkWidth, 0, 0),
            new Vector3Int(0, 0, GameData.ChunkWidth),
            new Vector3Int(0, 0, -GameData.ChunkWidth),
        };

        if (includeSelf && !chunksRebuiltinFrame.Contains(chunkPos))
        {
            if (chunks.TryGetValue(chunkPos, out var selfChunk))
            {
                StartCoroutine(DelayRebuild(selfChunk, 0));
                chunksRebuiltinFrame.Add(chunkPos);
            }
        }

        foreach (var dir in directions)
        {
            Vector3Int neighbourPos = chunkPos + dir;

            if (chunksRebuiltinFrame.Contains(neighbourPos))
                continue;

            if (chunks.TryGetValue(neighbourPos, out var neighbour))
            {
                StartCoroutine(DelayRebuild(neighbour, 0.05f));
                chunksRebuiltinFrame.Add(neighbourPos);
            }
        }
    }

    private void LateUpdate()
    {
        chunksRebuiltinFrame.Clear();
    }


}

  
